if (!hasInterface) exitWith {};
private _emp = "#lightpoint" createVehicleLocal [0,0,0];
_emp setLightDayLight true;
_emp setLightUseFlare true;
_emp setLightFlareMaxDistance 20000;
_emp setLightAmbient[1,0.5,1];
_emp setLightColor[0.3,0.2,1];
_emp setLightBrightness 6660;
_emp setLightFlareSize 6660;
_emp setPosASL (getPosASL gl_emp);
sleep random 1;
gl_emp say2D ["buzzer", 20000, 1];
_emp setLightBrightness 5550;
_emp setLightFlareSize 5550;
_handle2 = [{if (currentVisionMode player == 1) then {player action ["nvGogglesOff", player]}}, 0, []] call CBA_fnc_addPerFrameHandler;
sleep random 3;
_emp setLightBrightness 5000;
_emp setLightFlareSize 5000;
sleep random 2;
_emp setLightBrightness 4500;
_emp setLightFlareSize 4500;
sleep random 2;
_emp setLightBrightness 4000;
_emp setLightFlareSize 4000;
sleep random 2;
_emp setLightBrightness 3500;
_emp setLightFlareSize 3500;
sleep random 2;
addCamShake [10, 5, 50];
_emp setLightBrightness 2000;
_emp setLightFlareSize 2000;
sleep random 2;
gl_emp say2D ["buzzer", 20000, 1];
deleteVehicle _emp;
