loudspeaker2 say3D ["countdown", 400, 1, true];
loudspeaker3 say3D ["countdown", 400, 1, true];
titleText ["<t color='#2cb0a5' shadow = 1 size='1.4'>Crossroads:</t><t color ='#FFFFFF' shadow = 2 size ='1.3'>Kurwa! Spóźniliście się. Wysadźcie to i uciekajcie jak najszybciej. Mamy przejebane.</t>", "PLAIN DOWN", -1, true, true];
sleep 11;
civilian reportRemoteTarget [trgt_1, 3600];
civilian reportRemoteTarget [trgt_2, 3600];
civilian reportRemoteTarget [trgt_3, 3600];
trgt_1 confirmSensorTarget [civilian, true];
trgt_2 confirmSensorTarget [civilian, true];
trgt_3 confirmSensorTarget [civilian, true];
vls_0 fireAtTarget [trgt_1, "weapon_vls_01"];
vls_3 fireAtTarget [trgt_1, "weapon_vls_01"];
addCamShake [15, 6, 25];
sleep random 2;
vls_1 fireAtTarget [trgt_2, "weapon_vls_01"];
vls_4 fireAtTarget [trgt_2, "weapon_vls_01"];
sleep random 1;
vls_2 fireAtTarget [trgt_3, "weapon_vls_01"];
vls_5 fireAtTarget [trgt_2, "weapon_vls_01"];
sleep 15;
vls_0 fireAtTarget [trgt_2, "weapon_vls_01"];
vls_3 fireAtTarget [trgt_1, "weapon_vls_01"];
addCamShake [18, 6, 35];
sleep random 2;
vls_1 fireAtTarget [trgt_3, "weapon_vls_01"];
vls_4 fireAtTarget [trgt_2, "weapon_vls_01"];
sleep random 1;
vls_2 fireAtTarget [trgt_1, "weapon_vls_01"];
vls_5 fireAtTarget [trgt_2, "weapon_vls_01"];
