_info = [player] call a3cs_nametag_fnc_getUnitData;
_imie = _info select 0;
_ranga = _info select 1;
sleep 0.5;
cutText ["", "BLACK FADED", 999];
playmusic "Track_R_09";
[0, 0] spawn BIS_fnc_cinemaBorder;
sleep 10;
titleFadeOut 0.8;
sleep 4;
titleText ["","BLACK OUT",2];
2 cutRsc ["RscLogoB","BLACK",0.01];
titleText ["","BLACK IN",2];
sleep 3;
titleText ["","BLACK OUT",2];
sleep 3;
2 cutRsc ["RscLogoA","BLACK",0.01];
titleText ["","BLACK IN",2];
sleep 3;
titleText ["","BLACK OUT",2];
sleep 3;
2 cutFadeOut 0;
titleText ["","BLACK IN",2];
[["Full Metal Jacket",2,3,4],["Wietnam",2,3,4],["22 Kwietnia 1968",2,3,4],[(_ranga + " " + _imie),2,3,4]] spawn BIS_fnc_EXP_camp_SITREP;

 titleCut ["", "BLACK IN", 8];
   a3cs_nametag_displayInterrupt = false;
 "dynamicBlur" ppEffectEnable true;
 "dynamicBlur" ppEffectAdjust [6];
 "dynamicBlur" ppEffectCommit 0;
 "dynamicBlur" ppEffectAdjust [0.0];
 "dynamicBlur" ppEffectCommit 5;
sleep 16;
[1, 1] spawn BIS_fnc_cinemaBorder;
sleep 10;
